# Afficher la table de 5.

In [ ]:
# table de 5:
# 0 * 5 = 0
# 1 * 5 = 5
# 2 * 5 = 10 
...
# 12 * 5 = 60

In [33]:
for table in range(0,21):
    print("Table de " + str(table))
    for i in range(0,13):
        print(str(i) + "*" + str(table) + " = " + str(i*table))

Table de 0
0*0 = 0
1*0 = 0
2*0 = 0
3*0 = 0
4*0 = 0
5*0 = 0
6*0 = 0
7*0 = 0
8*0 = 0
9*0 = 0
10*0 = 0
11*0 = 0
12*0 = 0
Table de 1
0*1 = 0
1*1 = 1
2*1 = 2
3*1 = 3
4*1 = 4
5*1 = 5
6*1 = 6
7*1 = 7
8*1 = 8
9*1 = 9
10*1 = 10
11*1 = 11
12*1 = 12
Table de 2
0*2 = 0
1*2 = 2
2*2 = 4
3*2 = 6
4*2 = 8
5*2 = 10
6*2 = 12
7*2 = 14
8*2 = 16
9*2 = 18
10*2 = 20
11*2 = 22
12*2 = 24
Table de 3
0*3 = 0
1*3 = 3
2*3 = 6
3*3 = 9
4*3 = 12
5*3 = 15
6*3 = 18
7*3 = 21
8*3 = 24
9*3 = 27
10*3 = 30
11*3 = 33
12*3 = 36
Table de 4
0*4 = 0
1*4 = 4
2*4 = 8
3*4 = 12
4*4 = 16
5*4 = 20
6*4 = 24
7*4 = 28
8*4 = 32
9*4 = 36
10*4 = 40
11*4 = 44
12*4 = 48
Table de 5
0*5 = 0
1*5 = 5
2*5 = 10
3*5 = 15
4*5 = 20
5*5 = 25
6*5 = 30
7*5 = 35
8*5 = 40
9*5 = 45
10*5 = 50
11*5 = 55
12*5 = 60
Table de 6
0*6 = 0
1*6 = 6
2*6 = 12
3*6 = 18
4*6 = 24
5*6 = 30
6*6 = 36
7*6 = 42
8*6 = 48
9*6 = 54
10*6 = 60
11*6 = 66
12*6 = 72
Table de 7
0*7 = 0
1*7 = 7
2*7 = 14
3*7 = 21
4*7 = 28
5*7 = 35
6*7 = 42
7*7 = 49
8*7 = 56
9*7 = 63
10*7 = 70
11*7 = 77
12*7 = 84
Table de 8
0*8 = 0
1*8 = 8
2*8 = 16
3*8 = 24
4*8 = 32
5*8 = 40
6*8 = 48
7*8 = 56
8*8 = 64
9*8 = 72
10*8 = 80
11*8 = 88
12*8 = 96
Table de 9
0*9 = 0
1*9 = 9
2*9 = 18
3*9 = 27
4*9 = 36
5*9 = 45
6*9 = 54
7*9 = 63
8*9 = 72
9*9 = 81
10*9 = 90
11*9 = 99
12*9 = 108
Table de 10
0*10 = 0
1*10 = 10
2*10 = 20
3*10 = 30
4*10 = 40
5*10 = 50
6*10 = 60
7*10 = 70
8*10 = 80
9*10 = 90
10*10 = 100
11*10 = 110
12*10 = 120
Table de 11
0*11 = 0
1*11 = 11
2*11 = 22
3*11 = 33
4*11 = 44
5*11 = 55
6*11 = 66
7*11 = 77
8*11 = 88
9*11 = 99
10*11 = 110
11*11 = 121
12*11 = 132
Table de 12
0*12 = 0
1*12 = 12
2*12 = 24
3*12 = 36
4*12 = 48
5*12 = 60
6*12 = 72
7*12 = 84
8*12 = 96
9*12 = 108
10*12 = 120
11*12 = 132
12*12 = 144
Table de 13
0*13 = 0
1*13 = 13
2*13 = 26
3*13 = 39
4*13 = 52
5*13 = 65
6*13 = 78
7*13 = 91
8*13 = 104
9*13 = 117
10*13 = 130
11*13 = 143
12*13 = 156
Table de 14
0*14 = 0
1*14 = 14
2*14 = 28
3*14 = 42
4*14 = 56
5*14 = 70
6*14 = 84
7*14 = 98
8*14 = 112
9*14 = 126
10*14 = 140
11*14 = 154
12*14 = 168
Table de 15
0*15 = 0
1*15 = 15
2*15 = 30
3*15 = 45
4*15 = 60
5*15 = 75
6*15 = 90
7*15 = 105
8*15 = 120
9*15 = 135
10*15 = 150
11*15 = 165
12*15 = 180
Table de 16
0*16 = 0
1*16 = 16
2*16 = 32
3*16 = 48
4*16 = 64
5*16 = 80
6*16 = 96
7*16 = 112
8*16 = 128
9*16 = 144
10*16 = 160
11*16 = 176
12*16 = 192
Table de 17
0*17 = 0
1*17 = 17
2*17 = 34
3*17 = 51
4*17 = 68
5*17 = 85
6*17 = 102
7*17 = 119
8*17 = 136
9*17 = 153
10*17 = 170
11*17 = 187
12*17 = 204
Table de 18
0*18 = 0
1*18 = 18
2*18 = 36
3*18 = 54
4*18 = 72
5*18 = 90
6*18 = 108
7*18 = 126
8*18 = 144
9*18 = 162
10*18 = 180
11*18 = 198
12*18 = 216
Table de 19
0*19 = 0
1*19 = 19
2*19 = 38
3*19 = 57
4*19 = 76
5*19 = 95
6*19 = 114
7*19 = 133
8*19 = 152
9*19 = 171
10*19 = 190
11*19 = 209
12*19 = 228
Table de 20
0*20 = 0
1*20 = 20
2*20 = 40
3*20 = 60
4*20 = 80
5*20 = 100
6*20 = 120
7*20 = 140
8*20 = 160
9*20 = 180
10*20 = 200
11*20 = 220
12*20 = 240

In [32]:
for x in range(-10,11):
    resultat_fonction = x*x + 3*x -2
    print('pour x = ' + str(x) + ' f(x)= ' + str(resultat_fonction))

pour x = -10 f(x)= 68
pour x = -9 f(x)= 52
pour x = -8 f(x)= 38
pour x = -7 f(x)= 26
pour x = -6 f(x)= 16
pour x = -5 f(x)= 8
pour x = -4 f(x)= 2
pour x = -3 f(x)= -2
pour x = -2 f(x)= -4
pour x = -1 f(x)= -4
pour x = 0 f(x)= -2
pour x = 1 f(x)= 2
pour x = 2 f(x)= 8
pour x = 3 f(x)= 16
pour x = 4 f(x)= 26
pour x = 5 f(x)= 38
pour x = 6 f(x)= 52
pour x = 7 f(x)= 68
pour x = 8 f(x)= 86
pour x = 9 f(x)= 106
pour x = 10 f(x)= 128